snapshot: bd2811455364277f6219d4e2d9088c9b73e78e73

diff --git a/bin/vcheck b/bin/vcheck
--- a/bin/vcheck
+++ b/bin/vcheck
@@ -35,7 +35,7 @@ LSVER='(?:-(?P<lsver>ls[0-9]+))?'
 SEMVER_REGEX="(?:$SEMVER_MAJOR$SEMVER_MINOR$SEMVER_PATCH$HOTFIX|$VER_YMD)$SEMVER_PRERELEASE$SEMVER_BUILDMETA$LSVER"
 export SEMVER_REGEX
 
-AUTO_CHECKS='(alpine_repo|aur|cat|codeberg|command|curl|curlapi|docker_exec|docker_inspect|docker_inspect_image|docker_printenv|docker_tags|flatpak|flatpak_appstream|forgejo|github|gitlab|github_tags|gitlab|pacman)(_latest)?'
+AUTO_CHECKS='(alpine_repo|aur|cat|codeberg|command|curl|curlapi|docker_exec|docker_inspect|docker_inspect_image|docker_printenv|docker_tags|flatpak|flatpak_appstream|forgejo|github|github_tags|gitlab|gitlab_tags|pacman)(_latest)?'
 export AUTO_CHECKS
 
 # Handle temp files
@@ -580,7 +580,8 @@ _auto_check() { # helper_function
   # log -d -d -d "Running: ${FUNCNAME[0]} $*"
   log -d "Running: ${FUNCNAME[0]} $*"
 
-  local remove=() search=() project tmp jqfilter sedstring skipverfilter=false
+  local remove=() search=() sedstrings=() project tmp jqfilter sedstring
+  local skipverfilter=false
   local opt OPTARG OPTIND=1
   while getopts ":p:t:j:r:s:S:vV" opt; do
     case "$opt" in
@@ -589,7 +590,7 @@ _auto_check() { # helper_function
       j) jqfilter=$OPTARG ;;       # Uses last one given
       r) remove+=("$OPTARG") ;;
       s) search+=("$OPTARG") ;;
-      S) sedstring=$OPTARG ;;      # Uses last one given
+      S) sedstrings=("$OPTARG") ;;      # Uses last one given
       v) skipverfilter=true ;;
       V) skipverfilter=false ;;
       *) log -w "Invalid flag ($OPTARG)" ;;
@@ -632,6 +633,7 @@ _auto_check() { # helper_function
     github) out=$(_github_project "$project") ;;
     github_tags) out=$(_github_tags "$project") ;;
     gitlab) out=$(_gitlab_project "$project") ;;
+    gitlab_tags) out=$(_gitlab_tags "$project") ;;
     pacman)
       check_prog pacman "${FUNCNAME[0]} via ${FUNCNAME[1]}" || return 1
       out=$(pacman -Q "$project" 2> /dev/null)
@@ -673,11 +675,11 @@ _auto_check() { # helper_function
   log -d -d "tail -n1 output = '$out'"
 
   # Apply sedstring, if set
-  if [[ -n "$out" && -n "$sedstring" ]]; then
-    log -d -d -d "Using sed -r 's$sedstring'"
-    out=$(sed -r "s$sedstring" <<< "$out")
+  [[ -n "$out" ]] && for sedstring in "${sedstrings[@]}"; do
+    log -d -d -d "Using sed -r '$sedstring'"
+    out=$(sed -r "$sedstring" <<< "$out")
     log -d -d -d "sed output: $out"
-  fi
+  done
 
   # Apply versionfilter if $skipverfilter is false
   # shellcheck disable=SC2119
@@ -1274,6 +1276,31 @@ _gitlab_project() { # helper_function
   echo "$out"
 }
 
+_gitlab_tags() { # helper_function
+  log -d -d -d "Running: ${FUNCNAME[0]} $*"
+  check_prog jq "${FUNCNAME[0]} via ${FUNCNAME[1]}" || return 1
+  (( $# == 0 )) && { log -e "Argument required for ${FUNCNAME[0]}" ; return 1 ; }
+  [[ "$1" == "-h" ]] && { log "usage: ${FUNCNAME[0]} project/repo" ; return 0 ; }
+
+  local authstring=() err errmsg out
+  mapfile -t authstring < <(gen_authstring gitlab)
+
+  # URL-encode the owner/repo slug (GitLab requires this for namespaced projects)
+  local encoded
+  encoded=$(python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1], safe=''))" "$1")
+
+  err=$(maketemp)
+  out=$(maketemp)
+  echo "Looking up latest tag for $1 using gitlab api" >> "$err"
+  curl "${authstring[@]}" --no-progress-meter -Lo "$out" \
+    "https://gitlab.com/api/v4/projects/${encoded}/repository/tags?order_by=version&sort=desc&per_page=1" 2>> "$err"
+  log -d -d -d "curl output: $(cat "$out")"
+  out=$(jq -r '.[0].name' "$out" 2> /dev/null)
+  errmsg=$(cat "$err")
+  [[ -n "$errmsg" ]] && log -d "$sw: $errmsg"
+  echo "$out"
+}
+
 _github_tags() { # helper_function
   log -d -d -d "Running: ${FUNCNAME[0]} $*"
   check_prog jq "${FUNCNAME[0]} via ${FUNCNAME[1]}" || return 1
@@ -1485,43 +1512,6 @@ empiretech_camera_latest() {
   check_prog xmllint || return 1
   curl --no-progress-meter "https://empiretech01.com/pages/download-firmwares" | \
     xmllint --html --xpath "//div[@class='firmwares_content_container']/div[1][contains(text(), 'IPC-Color4K-T-S2')]/following-sibling::div[2]/text()" - 2> /dev/null
-}
-
-filestash_latest() { # no_auto
-  local app_version build_date
-  app_version=$(curl --no-progress-meter "https://raw.githubusercontent.com/mickael-kerjean/filestash/refs/heads/master/server/common/constants.go" | \
-    awk -F '"' '/^[[:space:]]*APP_VERSION[[:space:]]+=[[:space:]]+"/{print $2;exit}')
-  build_date=$(skopeo inspect docker://machines/filestash:latest | jq -r '.Created' 2> /dev/null)
-  build_date=$(echo "$build_date" | \
-    awk -F'[-T]' '/^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T/{print "." $1 $2 $3;exit}')
-  echo "$app_version$build_date"
-}
-
-frigate_docker() {
-  docker_compose_exec cat /opt/frigate/frigate/version.py | \
-    awk -F '"' '{sub(/-[^-]+$/,"",$2);print $2;exit}'
-}
-
-giftmanager_docker() {
-  docker_compose_exec cat /app/app.py | awk '$1=="app_version" {gsub(/"/,"");print $NF;exit}'
-}
-
-gitea_docker() {
-  docker_compose_exec gitea --version | awk '{print $3;exit}'
-}
-
-gitlab_docker() {
-  docker_compose_exec cat /opt/gitlab/version-manifest.txt | \
-    awk '$1=="gitlab-ce" { print $2; exit }'
-}
-
-gitlab_latest() { # no_auto
-  curl --no-progress-meter "https://gitlab.com/gitlab-org/gitlab-foss/-/raw/master/CHANGELOG.md" \
-    | awk '/^## [0-9]+\.[0-9]+\.[0-9]+ \([0-9]{4}-[0-9]{2}-[0-9]{2}\)/{print $2;exit}'
-}
-
-grafana_docker() {
-  docker_compose_exec grafana-server -v | awk '/^Version [0-9]/{print $2;exit}'
 }
 
 jellyfin_docker() {
@@ -1888,22 +1878,12 @@ splunk() {
   fi
 }
 
-splunk_latest() {
-  curl --no-progress-meter "https://www.splunk.com/en_us/download/splunk-enterprise.html" | \
-    awk -F'[<>]' '/<span class="version">/{print $3;exit}'
-}
-
 splunk_forwarder() {
   if [[ -x /opt/splunkforwarder/bin/splunk ]]; then
     awk -F= '/^VERSION/{print $2;exit}' /opt/splunkforwarder/etc/splunk.version
   elif [[ -x /Applications/splunkforwarder/bin/splunk ]]; then
     awk -F= '/^VERSION/{print $2;exit}' /Applications/splunkforwarder/etc/splunk.version
   fi
-}
-
-splunk_forwarder_latest() {
-  curl --no-progress-meter "https://www.splunk.com/en_us/download/universal-forwarder.html" | \
-    awk -F'[<>]' '/<span class="version">/{print $3;exit}'
 }
 
 splunk_unix_ta_latest() {
@@ -2491,7 +2471,7 @@ main() { # utility_function
       update=true
 
     # If sw is a list defined in the config, load its software in sw list
-    elif [[ " ${list_reserved_words[*]} " != *" $list "* && -s "$rcfile" ]]; then
+    elif [[ " ${list_reserved_words[*]} " != *" $list "* && "$list" != *!!* && -s "$rcfile" ]]; then
       log -d "Reading configfile for software list for ${list//\\/\\\\}"
       read -ra sw_list <<< "$(get_config_value "$rcfile" "$PROGNAME::${list//\\/\\\\}" "list" | tr '\n' ' ')"
       log -d "Setting software list to '${sw_list[*]}' for $list"
@@ -2503,7 +2483,7 @@ main() { # utility_function
     (( ${#sw_list[@]} == 0 )) && sw_list=("$list")
 
     unset rcoutput_file rcoutput_mode
-    if [[ -s "$rcfile" ]]; then
+    if [[ -s "$rcfile" && "$list" != *!!* ]]; then
       # output_mode
       rcvalue=() ; ! $output_mode_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"${list//\\/\\\\}" output_mode)
       (( ${#rcvalue[@]} > 0 )) && output_mode=${rcvalue[-1]} && \
@@ -2530,7 +2510,7 @@ main() { # utility_function
     # related to containers that were restarted within docker_seconds seconds
     if $update && [[ "$list" == docker ]]; then
       docker_seconds_local=$docker_seconds
-      if [[ -s "$rcfile" ]]; then
+      if [[ -s "$rcfile" && "$list" != *!!* ]]; then
         rcvalue=() ; ! $docker_seconds_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"$list" docker_seconds)
         (( ${#rcvalue[@]} > 0 )) && docker_seconds_local=${rcvalue[-1]}
       fi
@@ -2601,7 +2581,7 @@ main() { # utility_function
       [[ "$listname" == "$sw" ]] && unset listname
       tmp_name=$sw
 
-      rcvalue=() ; [[ -s "$rcfile" ]] && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"${sw//\\/\\\\}" check)
+      rcvalue=() ; [[ -s "$rcfile" && "$sw" != *!!* ]] && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"${sw//\\/\\\\}" check)
       (( ${#rcvalue[@]} > 0 )) && sw=${rcvalue[-1]} && sw_check_set=true && \
         log -d "Read check '$sw' for $tmp_name"
       sw_orig=$sw
@@ -2609,17 +2589,17 @@ main() { # utility_function
       # For dynamic/auto checks, strip off preceding 
       sw_name=$sw
       sw_tag=$(grep -Po "(?<=!!)$AUTO_CHECKS$" <<< "$sw_name")
-      while [[ "$sw_name" =~ ^(jq=|postsed=|remove=|search=|noskip_version_filter|skip_version_filter) ]]; do
+      while [[ "$sw_name" =~ ^(jq=|sed=|remove=|search=|noskip_version_filter|skip_version_filter) ]]; do
         case "$sw_name" in
           jq=*)
             tmpstring=${sw_name%%!!*}
             sw_name=${sw_name#jq=*!!}
             sw_jq+=(-j "${tmpstring#jq=}")       # The last one will be used
             ;;
-          postsed=*)
+          sed=*)
             tmpstring=${sw_name%%!!*}
-            sw_name=${sw_name#postsed=*!!}
-            sw_sed+=(-S "${tmpstring#postsed=}")  # The last one will be used
+            sw_name=${sw_name#sed=*!!}
+            sw_sed+=(-S "${tmpstring#sed=}")
             ;;
           remove=*)
             tmpstring=${sw_name%%!!*}
