snapshot: 0ef975a8dd4eacd739574c9214e7a228afc56638

diff --git a/bin/vcheck b/bin/vcheck
--- a/bin/vcheck
+++ b/bin/vcheck
@@ -284,7 +284,7 @@ gen_authstring() { # utility_function
   mapfile -t token < <(get_config_value "$file" "$section" "$key")
   if (( ${#token[@]} > 0 )); then
     echo "-H"
-    echo "Authorization: Bearer ${token[-1]}"
+    echo "Authorization: Bearer ${token[0]}"
     return 0
   fi
   log -d -d -d "Cannot get '$section' $key from '$file'"
@@ -790,17 +790,17 @@ _curl_api() { # helper_function
   (( ${#url[@]} == 0 ))      && { log -e "Could not read $check_name URL from $rcfile" ; return 1 ; }
   if (( ${#apikey[@]} > 0 )); then
     curl --no-progress-meter -Lo "$out" -X GET -H \
-      "Authorization: Bearer ${apikey[-1]}" \
-      "${url[-1]}"
+      "Authorization: Bearer ${apikey[0]}" \
+      "${url[0]}"
   elif (( ${#username[@]} > 0 || ${#password[@]} > 0 )); then
     (( ${#username[@]} == 0 )) && { log -e "Could not read $check_name Username from $rcfile" ; return 1 ; }
     (( ${#password[@]} == 0 )) && { log -e "Could not read $check_name Password from $rcfile" ; return 1 ; }
 
     curl --no-progress-meter -Lo "$out" -X GET -H \
-      "Authorization: Basic $(printf '%s:%s' "${username[-1]}" "${password[-1]}"|base64|tr -d '\n')" \
-      "${url[-1]}"
+      "Authorization: Basic $(printf '%s:%s' "${username[0]}" "${password[0]}"|base64|tr -d '\n')" \
+      "${url[0]}"
   else
-    curl --no-progress-meter -Lo "$out" -X GET "${url[-1]}"
+    curl --no-progress-meter -Lo "$out" -X GET "${url[0]}"
   fi
   log -d -d "Curl output: $out"
   cat "$out"
@@ -1080,7 +1080,7 @@ _docker_tags() { # helper_function
   if ${useskopeo:-false} && command -v skopeo &> /dev/null; then
     if (( ${#token[@]} > 0 && ${#username[@]} > 0 )); then
       authfile=$(maketemp)
-      hash=$(printf "%s:%s" "${username[-1]}" "${token[-1]}" | base64 | tr -d '\n')
+      hash=$(printf "%s:%s" "${username[0]}" "${token[0]}" | base64 | tr -d '\n')
       printf '{\n\t"auths": {\n\t\t"%s": {\n\t\t\t"auth": "%s"\n\t\t}\n\t}\n}\n' "$site" "$hash" > "$authfile"
       skopeoargs=("--authfile=$authfile")
     fi
@@ -1105,7 +1105,7 @@ _docker_tags() { # helper_function
           log -d -d "Connecting to hub.docker.com to get token"
           out=$(maketemp)
           curl --no-progress-meter -fo "$out" --max-time 15 -X POST -H "Content-Type: application/json" \
-            -d "{\"username\": \"${username[-1]}\", \"password\": \"${token[-1]}\"}" \
+            -d "{\"username\": \"${username[0]}\", \"password\": \"${token[0]}\"}" \
             "https://hub.docker.com/v2/users/login"
           if [[ -s "$out" ]]; then
             out=$(jq -r '.token // ""' "$out" 2>/dev/null)
@@ -1124,7 +1124,7 @@ _docker_tags() { # helper_function
           log -d -d "Connecting to ghcr.io to get token"
           out=$(maketemp)
           curl --no-progress-meter -Lo "$out" "https://ghcr.io/token?service=ghcr.io&scope=repository:${org:+$org/}$repo:pull" \
-             -u "${username[-1]}:${token[-1]}"
+             -u "${username[0]}:${token[0]}"
           if [[ -s "$out" ]]; then
             out=$(jq -r '$j.token // ""' "$out" 2>/dev/null)
             [[ -n "$out" ]] && authstring=("-H" "Authorization: Bearer $out") && \
@@ -1345,7 +1345,7 @@ myaur_package() { # helper_function
   [[ ! -s "$rcfile" ]] && { log -e "Cannot read $rcfile for ${FUNCNAME[0]}" ; return 1; }
   mapfile -t url < <(get_config_value "$rcfile" private_aur url)
   (( ${#url[@]} == 0 )) && { log -e "Could not read ${FUNCNAME[0]} URL from $rcfile" ; return 1 ; }
-  out=$(curl --no-progress-meter "${url[-1]}/raw/branch/main/$1/PKGBUILD")
+  out=$(curl --no-progress-meter "${url[0]}/raw/branch/main/$1/PKGBUILD")
   log -d -d -d "Curl output: $out"
   [[ -n "$out" ]] && awk -F= '/^pkgver=/{pv=$2}/^pkgrel=/{pr=$2}END{printf "%s-%s\n",pv,pr;exit}' <<< "$out"
 }
@@ -1831,12 +1831,12 @@ slzb_core_latest() {
   (( ${#esptype[@]} == 0 )) && { log -e "Could not read ${FUNCNAME[0]} EspType from $rcfile" ; return 1 ; }
 
   local fw_url
-  fw_url=$(curl --no-progress-meter --compressed "${url[-1]}" 2>&1 | \
+  fw_url=$(curl --no-progress-meter --compressed "${url[0]}" 2>&1 | \
     awk -F"'" '/^const espFwInfoUrl[[:space:]]*=/{print $2;exit}')
   log -d -d "fw_url = $fw_url"
-  [[ ! $fw_url =~ ^https?:// ]] && { log -e "Could not get firmware url from ${url[-1]}" ; return 1 ; }
-  log -d -d "fw_url=${fw_url}${esptype[-1]}" >&2
-  out=$(curl --no-progress-meter "${fw_url}${esptype[-1]}")
+  [[ ! $fw_url =~ ^https?:// ]] && { log -e "Could not get firmware url from ${url[0]}" ; return 1 ; }
+  log -d -d "fw_url=${fw_url}${esptype[0]}" >&2
+  out=$(curl --no-progress-meter "${fw_url}${esptype[0]}")
   log -d -d "Curl Output: $out"
   [[ -n "$out" ]] && out=$(jq -rn --argjson j "$out" '$j.["fw"][] | select(.dev == false) | .ver' 2> /dev/null)
   log -d -d "Jq Output: $out"
@@ -1859,11 +1859,11 @@ slzb_radio_latest() {
   (( ${#type[@]} == 0 )) && { log -e "Could not read ${FUNCNAME[0]} Type from $rcfile" ; return 1 ; }
 
   local fw_url
-  fw_url=$(curl --no-progress-meter --compressed "${url[-1]}" 2>&1 | \
+  fw_url=$(curl --no-progress-meter --compressed "${url[0]}" 2>&1 | \
     awk -F"'" '/^const zbFwInfoUrl[[:space:]]*=/{print $2;exit}')
   [[ ! $fw_url =~ ^https?:// ]] && return 1
   curl --no-progress-meter "$fw_url" | \
-    jq -r --arg chip "${chip[-1]}" --arg type "${type[-1]}" \
+    jq -r --arg chip "${chip[0]}" --arg type "${type[0]}" \
       '.[$chip][] | select(.type == $type) | .rev' 2> /dev/null| \
     sort -V | \
     tail -n1
@@ -2192,7 +2192,7 @@ main() { # utility_function
   # Read configuration settings
   if [[ -z "$exec_user" && -s "$rcfile" ]]; then
     mapfile -t arr < <(get_config_value "$rcfile" "$PROGNAME" user)
-    (( ${#arr[@]} > 0 )) && exec_user=${arr[-1]}
+    (( ${#arr[@]} > 0 )) && exec_user=${arr[0]}
     unset arr
   fi
 
@@ -2203,28 +2203,28 @@ main() { # utility_function
   # Read configuration file options
   if [[ -s "$rcfile" ]]; then
     rcvalue=(); mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME" cache_dir)
-    (( ${#rcvalue[@]} > 0 )) && cache_dir=${rcvalue[-1]}
+    (( ${#rcvalue[@]} > 0 )) && cache_dir=${rcvalue[0]}
 
     rcvalue=() ; ! $cache_lifetime_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME" cache_lifetime)
-    [[ ${#rcvalue[@]} -gt 0 && ${rcvalue[-1]} =~ ^[0-9]+$ ]] && cache_lifetime=${rcvalue[-1]}
+    [[ ${#rcvalue[@]} -gt 0 && ${rcvalue[0]} =~ ^[0-9]+$ ]] && cache_lifetime=${rcvalue[0]}
 
     rcvalue=() ; ! $retry_delay_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME" retry_delay)
-    [[ ${#rcvalue[@]} -gt 0 && ${rcvalue[-1]} =~ ^([0-9]+|\.[0-9]+|[0-9]+\.[0-9]+)$ ]] && retry_delay=${rcvalue[-1]}
+    [[ ${#rcvalue[@]} -gt 0 && ${rcvalue[0]} =~ ^([0-9]+|\.[0-9]+|[0-9]+\.[0-9]+)$ ]] && retry_delay=${rcvalue[01]}
 
     rcvalue=() ; mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME" max_retries)
-    [[ ${#rcvalue[@]} -gt 0 && ${rcvalue[-1]} =~ ^[0-9]+$ ]] && max_retries=${rcvalue[-1]}
+    [[ ${#rcvalue[@]} -gt 0 && ${rcvalue[0]} =~ ^[0-9]+$ ]] && max_retries=${rcvalue[0]}
 
     rcvalue=() ; ! $compose_file_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME" compose_file)
-    (( ${#rcvalue[@]} > 0 )) && compose_file=${rcvalue[-1]}
+    (( ${#rcvalue[@]} > 0 )) && compose_file=${rcvalue[0]}
 
     rcvalue=() ; ! $docker_seconds_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME" docker_seconds)
-    [[ ${#rcvalue[@]} -gt 0 && ${rcvalue[-1]} =~ ^[0-9]+$ ]] && docker_seconds=${rcvalue[-1]}
+    [[ ${#rcvalue[@]} -gt 0 && ${rcvalue[0]} =~ ^[0-9]+$ ]] && docker_seconds=${rcvalue[0]}
 
     rcvalue=() ; ! $printer_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME" printer)
-    (( ${#rcvalue[@]} > 0 )) && PRINTER=${rcvalue[-1]}
+    (( ${#rcvalue[@]} > 0 )) && PRINTER=${rcvalue[0]}
 
     rcvalue=() ; ! $sudo_user_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME" sudo_user)
-    (( ${#rcvalue[@]} > 0 )) && sudo_user=${rcvalue[-1]}
+    (( ${#rcvalue[@]} > 0 )) && sudo_user=${rcvalue[0]}
 
     # Deal with multiple sudo_regex lines
     local rcsudo_regex
@@ -2236,18 +2236,18 @@ main() { # utility_function
     fi
 
     rcvalue=() ; mapfile -t rcvalue < <(get_config_value "$rcfile" mqtt server)
-    (( ${#rcvalue[@]} > 0 )) && mqtt_server=${rcvalue[-1]}
+    (( ${#rcvalue[@]} > 0 )) && mqtt_server=${rcvalue[0]}
     rcvalue=() ; mapfile -t rcvalue < <(get_config_value "$rcfile" mqtt username)
-    (( ${#rcvalue[@]} > 0 )) && mqtt_username=${rcvalue[-1]}
+    (( ${#rcvalue[@]} > 0 )) && mqtt_username=${rcvalue[0]}
     rcvalue=() ; mapfile -t rcvalue < <(get_config_value "$rcfile" mqtt password)
-    (( ${#rcvalue[@]} > 0 )) && mqtt_password=${rcvalue[-1]}
+    (( ${#rcvalue[@]} > 0 )) && mqtt_password=${rcvalue[0]}
 
     rcvalue=() ; ! $host_name_set && mapfile -t rcvalue < <(get_config_value "$rcfile" mqtt host_name)
-    [[ ${#rcvalue[@]} -gt 0 && ${rcvalue[-1]} =~ ^[0-9]+$ ]] && host_name=${rcvalue[-1]}
+    [[ ${#rcvalue[@]} -gt 0 && ${rcvalue[0]} =~ ^[0-9]+$ ]] && host_name=${rcvalue[0]}
     rcvalue=() ; ! $ink_topic_set && mapfile -t rcvalue < <(get_config_value "$rcfile" mqtt ink_topic)
-    [[ ${#rcvalue[@]} -gt 0 && ${rcvalue[-1]} =~ ^[0-9]+$ ]] && ink_topic=${rcvalue[-1]}
+    [[ ${#rcvalue[@]} -gt 0 && ${rcvalue[0]} =~ ^[0-9]+$ ]] && ink_topic=${rcvalue[0]}
     rcvalue=() ; ! $prepend_name_set && mapfile -t rcvalue < <(get_config_value "$rcfile" mqtt prepend_name)
-    [[ ${#rcvalue[@]} -gt 0 && ${rcvalue[-1]} =~ ^[0-9]+$ ]] && prepend_name=${rcvalue[-1]}
+    [[ ${#rcvalue[@]} -gt 0 && ${rcvalue[0]} =~ ^[0-9]+$ ]] && prepend_name=${rcvalue[0]}
 
   fi # if [[ -s "$rcfile" ]]; then
 
@@ -2485,24 +2485,24 @@ main() { # utility_function
     if [[ -s "$rcfile" && "$list" != *!!* ]]; then
       # output_mode
       rcvalue=() ; ! $output_mode_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"${list//\\/\\\\}" output_mode)
-      (( ${#rcvalue[@]} > 0 )) && output_mode=${rcvalue[-1]} && \
+      (( ${#rcvalue[@]} > 0 )) && output_mode=${rcvalue[0]} && \
         case "$output_mode" in json);;mqtt)output_file=/dev/stdout;; *)output_mode=text;output_file=/dev/stdout;; esac
 
       # output_file
       rcvalue=() ; ! $output_file_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"${list//\\/\\\\}" output_file)
-      (( ${#rcvalue[@]} > 0 )) && output_file=${rcvalue[-1]} && output_mode=json
+      (( ${#rcvalue[@]} > 0 )) && output_file=${rcvalue[0]} && output_mode=json
       log -d "Reading ${list//\\/\\\\} config settings: output_file='$output_file' output_mode='$output_mode'"
 
       # prepend_name
       rcvalue=() ; ! $prepend_name_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"${list//\\/\\\\}" prepend_name)
-      (( ${#rcvalue[@]} > 0 )) && prepend_name=${rcvalue[-1]}
+      (( ${#rcvalue[@]} > 0 )) && prepend_name=${rcvalue[0]}
 
       # include_invalid
       rcvalue=() ; ! $include_invalid_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"${list//\\/\\\\}t" include_invalid)
-      (( ${#rcvalue[@]} > 0 )) && include_invalid=${rcvalue[-1]}
+      (( ${#rcvalue[@]} > 0 )) && include_invalid=${rcvalue[0]}
 
       rcvalue=() ; ! $compose_file_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"${list//\\/\\\\}" compose_file)
-      (( ${#rcvalue[@]} > 0 )) && compose_file=${rcvalue[-1]}
+      (( ${#rcvalue[@]} > 0 )) && compose_file=${rcvalue[0]}
     fi
 
     # If -L docker was given and docker_seconds is set, only look for checks
@@ -2511,7 +2511,7 @@ main() { # utility_function
       docker_seconds_local=$docker_seconds
       if [[ -s "$rcfile" && "$list" != *!!* ]]; then
         rcvalue=() ; ! $docker_seconds_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"$list" docker_seconds)
-        (( ${#rcvalue[@]} > 0 )) && docker_seconds_local=${rcvalue[-1]}
+        (( ${#rcvalue[@]} > 0 )) && docker_seconds_local=${rcvalue[0]}
       fi
 
       if [[ -n "$docker_seconds_local" ]]; then
@@ -2581,7 +2581,7 @@ main() { # utility_function
       tmp_name=$sw
 
       rcvalue=() ; [[ -s "$rcfile" && "$sw" != *!!* ]] && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"${sw//\\/\\\\}" check)
-      (( ${#rcvalue[@]} > 0 )) && sw=${rcvalue[-1]} && sw_check_set=true && \
+      (( ${#rcvalue[@]} > 0 )) && sw=${rcvalue[0]} && sw_check_set=true && \
         log -d "Read check '$sw' for $tmp_name"
       sw_orig=$sw
 
@@ -2645,25 +2645,25 @@ main() { # utility_function
       if [[ -s "$rcfile" ]]; then
         # See if check is defined
         # rcvalue=() ; mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"$list" check)
-        # (( ${#rcvalue[@]} > 0 )) && sw=${rcvalue[-1]} && \
+        # (( ${#rcvalue[@]} > 0 )) && sw=${rcvalue[0]} && \
         #   log -d "Read check '$sw' for $sw_name"
 
         # output_mode
         rcvalue=() ; ! $output_mode_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"$sw_name" output_mode)
-        (( ${#rcvalue[@]} > 0 )) && output_mode=${rcvalue[-1]} && \
+        (( ${#rcvalue[@]} > 0 )) && output_mode=${rcvalue[0]} && \
           case "$output_mode" in json);;mqtt)output_file=/dev/stdout;; *)output_mode=text;output_file=/dev/stdout;; esac
 
         # output_file
         rcvalue=() ; ! $output_file_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"$sw_name" output_file)
-        (( ${#rcvalue[@]} > 0 )) && output_file=${rcvalue[-1]} && output_mode=json
+        (( ${#rcvalue[@]} > 0 )) && output_file=${rcvalue[0]} && output_mode=json
         log -d "Reading $sw_name config settings: output_file='$output_file' output_mode='$output_mode'"
 
         # prepend_name
         rcvalue=() ; ! $prepend_name_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"$sw_name" prepend_name)
-        (( ${#rcvalue[@]} > 0 )) && prepend_name=${rcvalue[-1]}
+        (( ${#rcvalue[@]} > 0 )) && prepend_name=${rcvalue[0]}
 
         rcvalue=() ; ! $compose_file_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"$sw_name" compose_file)
-        (( ${#rcvalue[@]} > 0 )) && compose_file=${rcvalue[-1]}
+        (( ${#rcvalue[@]} > 0 )) && compose_file=${rcvalue[0]}
       fi
 
       # Set COMPOSE_FILE if necessary
@@ -2700,15 +2700,15 @@ main() { # utility_function
         log -d "Reading cache_lifetime retry_delay max_retries settings from config for $sw_name"
         # Check if this version check has a setting for cache_lifetime and use it if it does
         rcvalue=() ; mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"$sw_name" cache_lifetime)
-        (( ${#rcvalue[@]} > 0 )) && lifetime=${rcvalue[-1]}
+        (( ${#rcvalue[@]} > 0 )) && lifetime=${rcvalue[0]}
 
         # Check if this version check has a setting for retry_delay and use it if it does
         rcvalue=() ; mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"$sw_name" retry_delay)
-        (( ${#rcvalue[@]} > 0 )) && delay=${rcvalue[-1]}
+        (( ${#rcvalue[@]} > 0 )) && delay=${rcvalue[0]}
 
         # Check if this version check has a setting for max_retries and use it if it does
         rcvalue=() ; mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"$sw_name" max_retries)
-        (( ${#rcvalue[@]} > 0 )) && retries=${rcvalue[-1]}
+        (( ${#rcvalue[@]} > 0 )) && retries=${rcvalue[0]}
       fi
 
       # If printonly mode, add to list and continue to next
@@ -2769,9 +2769,9 @@ main() { # utility_function
           if [[ -s "$rcfile" ]]; then
             # Read config file to see if there are specific settings for $sw
             rcvalue=() ; mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"$sw_name" use_sudo)
-            (( ${#rcvalue[@]} > 0 )) && use_sudo=${rcvalue[-1]}
+            (( ${#rcvalue[@]} > 0 )) && use_sudo=${rcvalue[0]}
             rcvalue=() ; $use_sudo && ! $sudo_user_set && mapfile -t rcvalue < <(get_config_value "$rcfile" "$PROGNAME"::"$sw_name" sudo_user)
-            (( ${#rcvalue[@]} > 0 )) && sudo_user=${rcvalue[-1]}
+            (( ${#rcvalue[@]} > 0 )) && sudo_user=${rcvalue[0]}
           fi
 
           if $use_sudo && (( $(id -u) != 0 )); then
